[supervisord]
nodaemon=true
user=root
logfile=/var/log/cronjob/supervisord.log
pidfile=/var/run/supervisor/supervisord.pid
childlogdir=/var/log/cronjob

[program:cronjob-client]
command=python /app/cronjob_service.py
directory=/app
autostart=true
autorestart=true
startretries=3
stderr_logfile=/var/log/cronjob/cronjob-client.err.log
stdout_logfile=/var/log/cronjob/cronjob-client.out.log
user=root
environment=PYTHONPATH="/app:/shared:/newServiceArchitecture",PYTHONUNBUFFERED="1"

[program:cron]
command=cron -f
autostart=true
autorestart=true
startretries=3
stderr_logfile=/var/log/cronjob/cron.err.log
stdout_logfile=/var/log/cronjob/cron.out.log
user=root

[unix_http_server]
file=/var/run/supervisor.sock
chmod=0700

[supervisorctl]
serverurl=unix:///var/run/supervisor.sock

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface
