version: '3.8'
services:
  app:
    image: guyshacharacc/tzevaadom:latest
    environment:
      - TZ=Asia/Jerusalem
      - logLevel=INFO
      - url=https://api.tzevaadom.co.il/notifications
      - polling_interval=1000
      - live_logging_interval=2
      - raw_topic=my/mqtt/tzevaAdom/raw
      - error_topic=my/mqtt/tzevaAdom/error
      - url_sensor_alerts="sensor.pikud_haoref_alerts
      - notify_criteria_file=notifyCriteria.json
    secrets:
      - mqtt_broker
      - mqtt_username
      - mqtt_password
    volumes:
      - /Volumes/GuyMacExternal/Users/guyshachar/Projects/Python/PythonProjects/apps/tzevaAdom/history:/history
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      resources:
        limits:
          memory: 1g

  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_POLL_INTERVAL=30 # Check every 30 seconds

secrets:
  mqtt_broker:
    external: true
  mqtt_username:
    external: true
  mqtt_password:
    external: true