version: '3.8'
services:
  app:
    image: refportalservice:latest
    tty: true
    environment:
      - TZ=Asia/Jerusalem
      - logLevel=INFO
      - fileVersion=v8
      - swLevel=debug
      - approveGames=True
      - start24HoursWindowNotification=True
      - alwaysClosePage=True
      - mqttPublish=True
      - loadInterval=500
      - checkGames=True
      - checkReviews=True
      - concurrentPages=1
      - browserRenewal=30
      - twilioSend=False
      - twilioServiceId=MG7ec40f0e4baff9a172ad9e78cbc3d269
      - twilioFromMobile1=+14155238886
      - twilioFromMobile=+972533932474
      - twilioUseTemplate=True
      - twilioUseFreeText=False
      - twilioAddMedia=False
      - twilioOpenWindow=HX9cca11d6aba6c462ef0da97ef9d55d90
      - twilioNewGameContentSid=HXc778f502095de8425f0dee79ece9d355
      - twilioGameUpdateContentSid=HXe2c43cb7131ab345a4ec354dcc4d6233
      - twilioGameNoticeContentSid=HXc9438c8dad32dfd6aea090352d34b736
      - twilioNewReviewContentSid=HX9047136eb2b6743d57eee044790b176c
      - twilioReviewUpdateContentSid1=HX37c74e9d872d4ac5aee40f53dbb98bc8
      - registerReminderTime=1000
      - sendGeneralReminder=True
      - browserHeadless=True
      - alwaysRenewPages=True
      - apiServiceUrlBase=https://guyshachar.ddns.net:24501/api/
      - timeout=20000
      - timezone=Asia/Jerusalem
      - refIdsPartition=9
      - app=APP1
    volumes:
      - /Volumes/Macintosh\ HD/Users/guyshachar/Projects/Python/PythonProjects/apps/refPortal/data:/run/data
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  monitor:
    image: refportalmonitor:latest
    tty: true
    environment:
      - TZ=Asia/Jerusalem
      - logLevel=INFO
      - monitor_interval=5
      - timeout_seconds=30
      - restart_seconds=15
      - servicePrefix=refportal
    volumes:
      - /Volumes/Macintosh\ HD/Users/guyshachar/Projects/Python/PythonProjects/apps/refPortal/data:/run/data
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
