// Auto-generated client environment configuration
// Generated at: 2026-05-31T23:01:19.026Z
// DO NOT EDIT THIS FILE MANUALLY - IT WILL BE OVERWRITTEN

window.CLIENT_ENV = {
  "PWA_HTTP_PORT": "8082",
  "PWA_HTTPS_PORT": "8443",
  "PWA_BASE_URL": "https://pwa-dev.refereex.com",
  "API_BASE_URL": "https://api-dev.refereex.com",
  "WSS_BASE_URL": "api-dev.refereex.com",
  "apiServiceUrlBase": "https://api.refereex.com/",
  "rootServiceUrlBase": "https://www.refereex.com/",
  "docsServiceUrlBase": "https://www.refereex.com/docs/",
  "NODE_ENV": "development",
  "DEBUG_MODE": true,
  "BUILD_TIME": "2026-05-31T23:01:19.022Z",
  "VERSION": "v1.0.0",
  "FEATURES": {
    "PUSH_NOTIFICATIONS": true,
    "PUSH_NOTIFICATIONS_MUST": false,
    "OFFLINE_SUPPORT": true,
    "BACKGROUND_SYNC": true,
    "INSTALL_PROMPT": true,
    "CHAT_SYNC": true,
    "MAX_GPS_ACCURACY": 30,
    "START_MONITORING_HOURS_BEFORE_GAME": 3,
    "SPEED_THRESHOLD": 10,
    "MIN_DISTANCE_THRESHOLD": 0
  },
  "APP_NAME": "RefereeX",
  "APP_SHORT_NAME": "RefereeX",
  "SECURITY": {
    "ENABLE_PIN": false,
    "PIN_LENGTH": 4,
    "MAX_PAIR_ATTEMPTS": 3
  },
  "CORS_ORIGIN": "*"
};

// Export for ES6 modules
if (typeof module !== 'undefined' && module.exports) {
    module.exports = window.CLIENT_ENV;
}

// Make available globally
if (typeof global !== 'undefined') {
    global.CLIENT_ENV = window.CLIENT_ENV;
}

// Log environment info (only in debug mode)
if (window.CLIENT_ENV.DEBUG_MODE) {
    console.log('🌍 Client environment loaded:', window.CLIENT_ENV);
    console.log('📅 Generated at:', window.CLIENT_ENV.BUILD_TIME);
    console.log('🏷️ Version:', window.CLIENT_ENV.VERSION);
}

// Export for TypeScript/ES6 modules
export default window.CLIENT_ENV;
export const CLIENT_ENV = window.CLIENT_ENV;
