"""initial schema

Revision ID: 32dfecac8b61
Revises: 
Create Date: 2026-08-14 23:35:50.667602

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '32dfecac8b61'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('event_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('venue', sa.String(), nullable=False),
    sa.Column('start_time_utc', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_table('shows',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('show_id', sa.String(), nullable=False),
    sa.Column('event_id', sa.String(), nullable=False),
    sa.Column('schema_version', sa.String(), nullable=False),
    sa.Column('start_at_utc', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.event_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shows_event_id'), 'shows', ['event_id'], unique=False)
    op.create_index(op.f('ix_shows_show_id'), 'shows', ['show_id'], unique=True)
    op.create_table('zones',
    sa.Column('event_id', sa.String(), nullable=False),
    sa.Column('zone_id', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('qr_token', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.event_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('event_id', 'zone_id')
    )
    op.create_index(op.f('ix_zones_qr_token'), 'zones', ['qr_token'], unique=False)
    op.create_table('assets',
    sa.Column('show_pk', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('sha256', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['show_pk'], ['shows.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('show_pk', 'asset_id')
    )
    op.create_table('cues',
    sa.Column('show_pk', sa.Integer(), nullable=False),
    sa.Column('cue_id', sa.String(), nullable=False),
    sa.Column('offset_ms', sa.Integer(), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('params', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('zones', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['show_pk'], ['shows.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('show_pk', 'cue_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cues')
    op.drop_table('assets')
    op.drop_index(op.f('ix_zones_qr_token'), table_name='zones')
    op.drop_table('zones')
    op.drop_index(op.f('ix_shows_show_id'), table_name='shows')
    op.drop_index(op.f('ix_shows_event_id'), table_name='shows')
    op.drop_table('shows')
    op.drop_table('events')
    # ### end Alembic commands ###
